# tmuxdesk fleet definition
# name       ssh_alias    sigil  ip
hyle         hyle         🜂      173.212.203.211
hub2         hub2         ∴      149.102.137.139
finml        finml        ☰      5.189.145.105
karlsruhe    karlsruhe    ∞      45.90.121.59
nabla        nabla        ∇      35.252.20.194
